# fly.toml app configuration file generated for chatbot-telegrem-nameless-water-1268 on 2025-04-03T13:02:52+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatbot-telegrem-nameless-water-1268'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
